import { describe, expect, it } from "vitest";
import { FlashForgeClient } from "../src/worker/transports/FlashForgeClient.js";
import { MoonrakerClient } from "../src/worker/MoonrakerClient.js";

// Mirrors the vendored plugin-sdk worker-rpc-host serializeFetchBody
// (not exported): string -> utf8, Buffer/Uint8Array -> base64.
function serializeFetchBody(body: unknown): { body: string; bodyEncoding: string } {
  if (typeof body === "string") return { body, bodyEncoding: "utf8" };
  if (body instanceof Uint8Array) {
    return {
      body: Buffer.from(body.buffer, body.byteOffset, body.byteLength).toString("base64"),
      bodyEncoding: "base64",
    };
  }
  return { body: String(body), bodyEncoding: "utf8" };
}

const PAYLOAD = Buffer.concat([
  Buffer.from("; generated by slicer ", "ascii"),
  Buffer.from([0xe2, 0x80, 0x94]), // em-dash (UTF-8)
  Buffer.from(" nozzle 215", "ascii"),
  Buffer.from([0xb0]), // latin1 degree sign
  Buffer.from("C\nG28\n", "ascii"),
  Buffer.from([0xff]),
  Buffer.from("\n", "ascii"),
]);

const silent = { info() {}, warn() {}, error() {}, debug() {} };

function capture(respond: () => Response) {
  const calls: { url: string; init: { body?: unknown; headers?: Record<string, string> } }[] = [];
  const http = {
    fetch: async (url: string, init?: unknown) => {
      calls.push({ url, init: (init ?? {}) as never });
      return respond();
    },
  };
  return { http, calls };
}

function assertFilePart(body: unknown, boundary: string) {
  expect(typeof body).not.toBe("string");
  expect(body instanceof Uint8Array).toBe(true);
  const buf = Buffer.from(body as Uint8Array);
  const start = buf.indexOf(Buffer.from("\r\n\r\n")) + 4;
  const end = buf.indexOf(Buffer.from(`\r\n--${boundary}`), start);
  expect(buf.subarray(start, end).equals(PAYLOAD)).toBe(true);
  const ser = serializeFetchBody(body);
  expect(ser.bodyEncoding).toBe("base64");
  expect(Buffer.from(ser.body, "base64").length).toBe(buf.length);
  expect(Buffer.from(ser.body, "base64").equals(buf)).toBe(true);
}

function boundaryOf(headers: Record<string, string> | undefined): string {
  const ct = headers?.["Content-Type"] ?? "";
  return ct.replace(/^.*boundary=/, "");
}

describe("uploadGcode sends non-ASCII bytes byte-exact", () => {
  it("FlashForge: Buffer body, file part identical, fileSize == input length", async () => {
    const { http, calls } = capture(
      () => new Response(JSON.stringify({ code: 0, message: "Success" }), { status: 200 }),
    );
    const client = new FlashForgeClient({
      baseUrl: "http://printer.test:8898",
      serialNumber: "SN1",
      checkCode: "cc",
      http: http as never,
      logger: silent as never,
      pollIntervalMs: 60_000,
    });
    await client.uploadGcode("a.gcode", PAYLOAD);
    expect(calls).toHaveLength(1);
    const { body, headers } = calls[0].init;
    expect(headers?.fileSize).toBe(String(PAYLOAD.length));
    expect(headers?.printNow).toBe("false");
    assertFilePart(body, boundaryOf(headers));
  });

  it("Moonraker: Buffer body, file part identical (with path/root fields)", async () => {
    const { http, calls } = capture(
      () =>
        new Response(
          JSON.stringify({ result: { item: { path: "a.gcode", root: "gcodes", size: 1, modified: 0 } } }),
          { status: 201, headers: { "Content-Type": "application/json" } },
        ),
    );
    const client = new MoonrakerClient({
      baseUrl: "http://printer.test:7125",
      apiKey: null,
      http: http as never,
      logger: silent as never,
    });
    await client.uploadGcode("a.gcode", PAYLOAD, { path: "sub", root: "gcodes" });
    expect(calls).toHaveLength(1);
    const { body, headers } = calls[0].init;
    const b = boundaryOf(headers);
    assertFilePart(body, b);
    const text = Buffer.from(body as Uint8Array).toString("latin1");
    expect(text).toContain(`name="path"\r\n\r\nsub\r\n`);
    expect(text.endsWith(`--${b}--\r\n`)).toBe(true);
  });
});
